analisis_importaciones = """
SELECT
     CUSTOMER_NAME AS IMPORTADOR
    ,PROVIDER_NAME AS PROVEEDOR
    ,ORIGIN_COUNTRY AS PAIS_ORIGEN
    ,PROVENANCE_COUNTRY AS PAIS_PROCEDENCIA
    ,TARIFF_LEVEL3_DESCRIPTION AS PARTIDA
    ,UNIT_DESCRIPTION AS TIPO_UNIDADES
    ,DATE_TRUNC(MONTH, IMPORT_DATE) AS MES
    ,IMPORT_DATE AS FECHA
    ,FOB_VALUE_USD AS FOB
    ,CIF_VALUE_USD AS CIF
    ,NET_WEIGHT_KILOGRAMS AS PESO_NETO
    ,QUANTITY_UNITS AS UNIDADES
FROM
    ANALIZA.ANALIZA_IMPORTS_SOURCE
WHERE 1=1
    AND IMPORT_DATE >= '2022-01-01' 
    AND IMPORT_DATE <= '2024-10-31'
    AND HS_CODE_1 IN  ('72','73','34','39','32','87','84')
"""